package templates

var (
	EndpointSet = `// Code generated by og. DO NOT EDIT.
package {{ .Package }}

import (
	"github.com/go-kit/kit/endpoint"
)

// EndpointSet implements {{ .Interface.Name }} API and used for transport purposes.
type EndpointSet struct {
{{- range .Interface.Methods }}
	{{ .Name }}Endpoint endpoint.Endpoint
{{- end }}
}

func NewEndpointSet(svc {{ .ServicePackage }}.{{ .Interface.Name }}) EndpointSet {
	return EndpointSet{
{{- range .Interface.Methods }}
	{{ .Name }}Endpoint: New{{ .Name }}Endpoint(svc),
{{- end }}
	}
}
`
)
