package templates

var (
	Endpoints = `// Code generated by og. DO NOT EDIT.
package {{ .Package }}

import (
	"context"
	"github.com/go-kit/kit/endpoint"
)

{{ $in:= .Interface.Name }}
{{ $sp:= .ServicePackage }}

{{ range .Interface.Methods }}
func New{{ .Name }}Endpoint(svc {{ $sp }}.{{ $in }}) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		{{- if .Args.HasContext }}
		{{ .Results.Args.UnexportedNames }} := svc.{{ .Name }}(request.(*{{ .Name }}Request).Args(ctx))
		{{- else }}
		{{ .Results.Args.UnexportedNames }} := svc.{{ .Name }}(request.(*{{ .Name }}Request).Args())
		{{- end }}
		{{- if .Results.Args.HasError }}
		if err != nil {
			return nil, err
		}
		{{- end }}
		return New{{ .Name }}Response({{ .Results.Args.UnexportedNames "err" }}), nil
	}
}
{{ end }}
`
)
