package templates

var (
	Endpoints = `// Code generated by og. DO NOT EDIT.
package {{ .Package }}

import (
	"context"
	"github.com/go-kit/kit/endpoint"
)

{{ $in:= .Interface.Name }}
{{ $sp:= .ServicePackage }}

{{ range .Interface.Methods }}
func New{{ .Name }}Endpoint(svc {{ $sp }}.{{ $in }}) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
{{ if .Args }} 
{{- if eq (index .Args 0).Type.String "context.Context" }}
		return New{{ .Name }}Response(svc.{{ .Name }}(request.(*{{ .Name }}Request).Args(ctx))), nil
{{ else }}
		return New{{ .Name }}Response(svc.{{ .Name }}(request.(*{{ .Name }}Request).Args())), nil
{{ end -}}
{{ else }}
		return New{{ .Name }}Response(svc.{{ .Name }}()), nil
{{ end }}
	}
}
{{ end }}
`
)
